### ISSUE TITLE
Scope of mapview (colours, labels etc.)

### ISSUE THREAD

**Issue by UniquePhilosophy** [TomSchimansky/TkinterMapView#2]
Evening Tom,

Hope you're well, we talked earlier because I thought there was an issue with your software. I thought I'd open a discussion with you if you're happy to discuss the scope of the project? What are your plans for TkinterMapView?

I'm particularly interested in different coloured markers and adding labels to markers (tooltips/popups). I had a peep on some of your source files to see if I could change some attributes and maybe affect the colour of the markers. Unfortunately I could only find the attribute for the colour of the dark red circle inside the marker.

It has occurred to me however that the map may be displayed on a canvas? Since this is the case, is it possible for people to add their own images **on top of** the OSM map?

Thanks!

**Comment by TomSchimansky** [comment]
Hey, you're right, the map is drawn on a tkinter.Canvas. The map tiles are PIL images and are drawn on the canvas with canvas.create_image(). The markers and path are drawn on the canvas too. You can access the canvas by using the attribute `map_widget.canvas` and draw on there whatever you want. But to create a tooltip or popup on the canvas itself would be very difficult I think, because you would havee to draw everything by yourself.
But I can easily add options to edit the colors when creating a marker and I can also add a command attribute, where you can give a function which will be called when you click on a particular marker. Then you could open a menu or extra information about that marker alongside the map_widget with normal tkinter elements.
I will add the options for the colors today or tomorrow, but if you want to edit the marker by yourself, you should edit the .draw() function in canvas_position_marker.py. There the circle, the triangle and the text of the marker are drawn:

<img width="1231" alt="Bildschirmfoto 2022-02-24 um 20 13 31" src="https://user-images.githubusercontent.com/66446067/155591961-f4433334-15a1-4662-981c-cf23252b63b3.png">

**Comment by UniquePhilosophy** [comment]
That is absolutely fantastic! I like your idea for having a function called when a marker is clicked, that would be perfect to be honest. That gives users a lot of freedom with the markers! I'll take everything you've said on board and look out for further updates as well. Thanks for being such a legend lol

**Comment by TomSchimansky** [comment]
Version 1.2 is now on pip. I added support for images above the markers which, they can have a command and custom Colors. I created a few examples in `examples/map_view_custom_marker_example.py`. You can add an image to the marker
and change the visibility of the image by calling marker.hide_image(True/False) and by defining a zoom range in which the image will be visible. And you can change the font now. The arguments a described here: [position markers](https://github.com/TomSchimansky/TkinterMapView#create-position-markers)
Feel free to ask if you want more info on the arguments or have some ideas on improvements.
