### ISSUE TITLE
Question about frame rate

### ISSUE THREAD

**Issue by planyway** [TomSchimansky/TkinterMapView#3]
Thanks for the project and I have a suggestion: 
Currently if I drag and release the mouse, your map moves very smoothly when it is fading automatically. If I use my mouse to drag the map roughly in the same velocity like the fading part does, the movement look slightly less smooth, exactly like your gif here. Is there a way to fix?
[![圖片](https://user-images.githubusercontent.com/92812919/155875713-ee911258-afa0-48e4-9adb-4225c208fb12.png)](https://github.com/TomSchimansky/TkinterMapView/blob/main/documentation_images/customtkinter_example.gif)

**Comment by TomSchimansky** [comment]
I think I know what you mean, but maybe it just looks like its smoother because it gets so slow when its fading. So when its fading, I update the map as fast as possible, it can't get faster than that without optimisations. And when you move the map with the mouse, the map is updated when there is a mouse-move event on the tkinter.Canvas. Maybe the tkinter events are not triggered that often, as it would be possible and there are breaks in between the event calls where nothing is done. But I don't think I can do anything about that. I could try to fill these breaks with an update call of my own and repeat the last movement, but I don't know if that will look good.
The Tkinter.Canvas is very slow and it's just not suitable for a fullscreen or large map widget. Maybe I will try to improve the performance further, but I think the rendering on the canvas (canvas.update() call) is by far the most time consuming operation in the process, and I can't do anything about that.

**Comment by planyway** [comment]
```
import tkinter as tk

root = tk.Tk()

w = tk.Canvas(root, width = 400, height = 200)
w.pack()

def paint(event):
        x1, y1 = (event.x), (event.y - 1)
        x2, y2 = (event.x), (event.y + 1)
        w.create_oval(x1, y1, x2, y2, fill = "red")

w.bind("<Motion>", paint)

tk.Label(root, text = "Drag to draw").pack(side = "bottom")

root.mainloop()
```
By drawing a line slowly or quickly, you can test how fast your computer triggers the mouse-move event with this code.

**Comment by TomSchimansky** [comment]
Yeah, but I think you can be sure the triggering of events is not a problem, because when you make the map_view extremely small, then moving gets completely smooth. That means the lag is just coming from the size of the canvas, and from the increased rendering time.
