### ISSUE TITLE
Question about offline usage

### ISSUE THREAD

**Issue by JayJayYo** [TomSchimansky/TkinterMapView#4]
Hey first of all great Project, 

i have a quick question, is it possible to use this offline without the workaround with a local hosted map tile server?

e.g something like a caching function or a setting to specify a local map/tiles?

**Comment by TomSchimansky** [comment]
Currently there is no such option. But I already started to work on a method to load tiles into a directory and then use them when there is no connection available. The TkinterMapView class already has a method called `load_offline_tiles`. But they can't be used at the moment. But if I have time, I will try to implement this, it shouldn't be too difficult.

**Comment by TomSchimansky** [comment]
I added offline usage with version 1.4 now. You can create a database and use it for the map widget.
You can specify to use the database only, or use the online server and database both, so that the database will
be only used when the connection breaks.
More information here: https://github.com/TomSchimansky/TkinterMapView/blob/main/examples/map_with%20offline_tiles.py

If you have any questions on this, feel free to ask.
