### ISSUE TITLE
Question about paths

### ISSUE THREAD

**Issue by BlaatVogel** [TomSchimansky/TkinterMapView#5]
Hello Tom,

Would it be possible to add similar functionality to paths that you added recently to markers? (styling, colours, callbacks?)

I've taken it upon myself to learn Python (a bit) and am trying to recreate some basic GUI items that I already have in a Matlab application. Amongst these items is the drawing of multiple polylines. I've found your tkintermapview and already succeeded in drawing a polyline by using your path option. However, for multiple paths of different categories, I'd like to have a visual difference between the paths. 

In this respect, I'm trying to understand how the paths work with the canvas of tkinter. Are these essentially sparsely filled bitmaps stacked ontop of each other or are these actually "clickable" lines? In the basis I'm trying to get a feeling how scalable the approach of using the canvas is to draw many polylines on a map.

Marcel

**Comment by TomSchimansky** [comment]
Hey, yeah that's possible, I can try to do it today to tomorrow. The path is a tkinter.canvas line object created like this in the canvas_path.py file:
```python
canvas_line = map_widget.canvas.create_line(canvas_line_positions, width=9, fill="#3E69CB", capstyle=tkinter.ROUND, joinstyle=tkinter.ROUND, tag="path")
```
And this can be clickable because you can bind events to objects of the canvas like this:
```python
map_widget.canvas.tag_bind(canvas_line, "<Button-1>", self.click)
```
So you can draw on the canvas whatever you want, also filled polygons would be possible. The only downside is that the tkinter.Canvas is not antialiased on Windows and Linux so the tkinter shapes don't look smooth there:
https://stackoverflow.com/questions/42887362/why-is-the-tkinter-render-quality-much-worse-on-windows
With images this is not a problem, but to do a path with images would be very difficult. Maybe I will replace the marker with an image created at runtime in the appropriate colors at some point so that it looks better on Windows.

**Comment by BlaatVogel** [comment]
Sounds great! It's too early for me to know whether the anti-aliasing will become problematic. I'll see your additions when you get around to it. Thank you in advance!

**Comment by TomSchimansky** [comment]
I added a `color` argument and a `command` argument to the path. You pass these to the `map_widget.set_path` function when creating a path. You can also pass a `name` argument to identify the path, when it gets passed to the command function. Here is an examples:

```python
map_widget = TkinterMapView(root_tk, width=1000, height=700, corner_radius=0)
map_widget.pack(fill="both", expand=True)

def path_click(path):
    print(f"path clicked: {path.name})

path_1 = map_widget.set_path([marker_2.position, marker_3.position], color="green", command=path_click, name="path1")
```
