### ISSUE TITLE
Zoom value limit at 19 ?

### ISSUE THREAD

**Issue by egourgand** [TomSchimansky/TkinterMapView#6]
Hello,

Great work !
I was looking for resources to create a prototype tool with data entry on a map and your work meets my needs perfectly.

I started adding new methods to the TkinterMapView class to manually edit the map. I'll share those code parts once I'm done if you're interested.

I have a question about the zoom value limit which is set to 19. I would like to zoom a bit more (20 or 21) but even changing the max_value in the library doesn't seem to work. Is there a reason for this limit?

Another question, I saw on Reddit and in the logs that you had implemented auto-resizing. Is it for the map widget to keep the same size as the window? If so, I can't get it to work. If I enlarge the window, the widget keeps the same size as when it was created.

Regards,

**Comment by TomSchimansky** [comment]
Hey, the limit of the zoom depends only on the tile server which is used. I use `https://a.tile.openstreetmap.org/{z}/{x}/{y}.png` as the standard tile server and this server provides tiles up to a zoom level of 19. The google tile server `https://mt0.google.com/vt/lyrs=m&hl=en&x={x}&y={y}&z={z}&s=Ga` I found provides tiles up to a zoom level of 22. If you find a tile server with a higher zoom level you can use it.

If you want the widget to resize with the window, you have to put in on the window so that it supports resizing like the other tkinter widgets. For the `.pack()` manager that would be something like: `map_widget.pack(fill="both", expand=True)`.
If you use a `.grid` then you have to give the row or column the map is in a weight with: `root.grid_rowconfigure(0, weight=1)`. And you have to put it in the grid with the sticky option: `map_widget.grid(row=0, column=0, sticky="nsew")`.
But that's the same how it works for a Frame or any other tkinter widget, you can look that up.
